### ISSUE TITLE
Cannot use ECJ 3.36.0 to compile Java 17 sources

### ISSUE THREAD

**Issue by UdoW** [TheMrMilchmann/gradle-ecj#27] opened 2024-02-06 08:12 UTC
I set in my build.gradle the ECJ version to 3.36.0 to use it for compiling Java 17 source files.

I get this error:

```
$ ./gradlew build

> Task :compileJava FAILED
source level should be comprised in between '1.3' and '1.8' (or '5', '5.0', ..., '8' or '8.0'): 17
```

Is compiling Java 17 source code not possible?

**Comment by TheMrMilchmann** [comment] 2024-05-01 10:28
Closing as I cannot reproduce this issue and did not received feedback.

**Closed by TheMrMilchmann** 2024-05-01 10:28 UTC
Labels: a:bug, was:invalid
